default-remote: local
remotes:
  local:
    addr: unix://
    public: false
  images:
    addr: https://mirrors.tuna.tsinghua.edu.cn/lxc-images/
    protocol: simplestreams
    public: true
aliases: {}
