#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc.bspwm &
picom &
~/.config/polybar/launch.sh
feh --bg-fill ~/picture/wallpaper/september-days-1830.jpg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fcitx5 &
clash-verge &
